name: Auto Push Ke App Script
on:
  push:
    branches:
      - main
jobs:
  auto-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Clasp
        run: bun install -g @google/clasp

      - name: Setup clasp credentials
        run: |
          echo "$CLASPRC_JSON" > ~/.clasprc.json
        env:
          CLASPRC_JSON: ${{ secrets.CLASPRC_JSON }}

      - name: Push to App Script
        run: clasp push -f